image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get install -y python python3.8
  - python3 -V
  - pip3 install pytest

test:
  script:
    - python3 -m pytest --junitxml=./coverage/report.xml

  artifacts:
      reports:
        cobertura: coverage/report.xml
