image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get install -y python3
  - apt-get install -y python3-pip
  - python3 -V
  - pip3 install pytest pytest-cov

test:
  script:
    - python3 -m pytest --cov=src/
    - coverage xml

  artifacts:
      reports:
        cobertura: coverage.xml
