image: ubuntu:latest

before_script:
  - python3 -version
  - pip3 install pytest

test:
  script:
    - python3 -m pytest --junitxml=./coverage/report.xml

  artifacts:
      reports:
        cobertura: coverage/report.xml
